#lang racket

(require scramble/regexp
         csse-scheduling/canonicalize)

(define catalog "2022-2026")

;; list extracted using
;; https://nextcatalog-admin.calpoly.edu/wen/2254/189-CSC/?osu=189-CSC
;; then checking the "show all courses box", then saving HTML and scraping it using this sxpath
;; query:
;; (sxpath '(// (div (@ id (equal? "offering-grid"))) table tbody tr td div))


(define (parse-clss-course-desc-row row)
  (match row
    [(regexp (px ^
                 (report (+ (chars [#\A #\Z])))
                 " "
                 (report (+ (chars [#\0 #\9]
                                   [#\A #\Z])))
                 " – " ;; that's not a regular hyphen...
                 )
             (list _ subject num))
     (canonicalize catalog subject num)]))

(define csc-courses
  (map parse-clss-course-desc-row
       '("CPE 101 – Fundamentals of Computer Science"
    "CPE 123 – Introduction to Computing"
    "CPE 202 – Data Structures"
    "CPE 203 – Project-Based Object-Oriented Programming and Design"
    "CPE 321 – Introduction to Computer Security"
    "CPE 357 – Systems Programming"
    "CPE 431 – Compiler Construction"
    "CPE 453 – Introduction to Operating Systems"
    "CPE 454 – Implementation of Operating Systems"
    "CPE 458 – Current Topics in Computer Systems"
    "CPE 471 – Introduction to Computer Graphics"
    "CPE 476 – Real-Time 3D Computer Graphics Software"
    "CPE 569 – Distributed Computing"
    "CSC 101 – Fundamentals of Computer Science"
    "CSC 121 – Computing for All I"
    "CSC 122 – Computing for All II"
    "CSC 123 – Introduction to Computing"
    "CSC 200 – Special Problems for Undergraduates"
    "CSC 202 – Data Structures"
    "CSC 203 – Project-Based Object-Oriented Programming and Design"
    "CSC 231 – Programming for Engineering Students"
    "CSC 232 – Computer Programming for Scientists and Engineers"
    "CSC 234 – C and Unix"
    "CSC 248 – Discrete Structures"
    "CSC 290 – Selected Topics"
    "CSC 300 – Professional Responsibilities"
    "CSC 304 – Software Engineering without Programming"
    "CSC 305 – Individual Software Design and Development"
    "CSC 307 – Introduction to Software Engineering"
    "CSC 308 – Software Engineering I"
    "CSC 309 – Software Engineering II"
    "CSC 312 – Computational Thinking for Educators"
    "CSC 313 – Teaching Computing"
    "CSC 314 – Software Design and Data Structures for Educators"
    "CSC 320 – Practical Computer Security for Everyone"
    "CSC 321 – Introduction to Computer Security"
    "CSC 323 – Cryptography Engineering"
    "CSC 325 – Introduction to Privacy: Policy and Technology"
    "CSC 344 – Music Programming"
    "CSC 349 – Design and  Analysis of Algorithms"
    "CSC 350 – Computing for Interactive Arts Capstone I"
    "CSC 357 – Systems Programming"
    "CSC 364 – Introduction to Networked, Distributed, and Parallel Computing"
    "CSC 365 – Introduction to Database Systems"
    "CSC 366 – Database Modeling, Design and Implementation"
    "CSC 369 – Introduction to Distributed Computing"
    "CSC 371 – Game Design"
    "CSC 377 – Introduction to Mixed Reality"
    "CSC 378 – Interactive Entertainment Engineering"
    "CSC 400 – Special Problems"
    "CSC 402 – Software Requirements Engineering"
    "CSC 405 – Software Construction"
    "CSC 406 – Senior Project - Software Deployment"
    "CSC 409 – Current Topics in Software Engineering"
    "CSC 410 – Software Evaluation"
    "CSC 421 – Binary Exploitation: Tools and Techniques"
    "CSC 424 – Software Security"
    "CSC 429 – Current Topics in Computer Security"
    "CSC 430 – Programming Languages"
    "CSC 431 – Compiler Construction"
    "CSC 436 – Mobile Application Development"
    "CSC 437 – Dynamic Web Development"
    "CSC 445 – Theory of Computation I"
    "CSC 448 – Bioinformatics Algorithms"
    "CSC 450 – Computing for Interactive Arts Capstone II"
    "CSC 453 – Introduction to Operating Systems"
    "CSC 454 – Implementation of Operating Systems"
    "CSC 458 – Current Topics in Computer Systems"
    "CSC 466 – Knowledge Discovery from Data"
    "CSC 468 – Database Management Systems Implementation"
    "CSC 471 – Introduction to Computer Graphics"
    "CSC 473 – Advanced Rendering Techniques"
    "CSC 474 – Computer Animation"
    "CSC 476 – Real-Time 3D Computer Graphics Software"
    "CSC 477 – Scientific and Information Visualization"
    "CSC 478 – Current Topics in Computer Graphics"
    "CSC 480 – Artificial Intelligence"
    "CSC 481 – Knowledge Based Systems"
    "CSC 482 – Speech and Language Processing"
    "CSC 484 – User-Centered Interface Design and Development"
    "CSC 486 – Human-Computer Interaction Theory and Design"
    "CSC 487 – Deep Learning"
    "CSC 490 – Selected Advanced Topics"
    "CSC 491 – Senior Project I"
    "CSC 492 – Senior Project II"
    "CSC 493 – Cooperative Education Experience"
    "CSC 496 – Selected Advanced Laboratory"
    "CSC 497 – Research Senior Project I"
    "CSC 498 – Research Senior Project II"
    "CSC 500 – Directed Study"
    "CSC 508 – Software Engineering I"
    "CSC 509 – Software Engineering II"
    "CSC 513 – Computing Education Research and Practice"
    "CSC 521 – Computer Security"
    "CSC 522 – Advanced Network Security"
    "CSC 524 – System Security"
    "CSC 530 – Languages and Translators"
    "CSC 540 – Theory of Computation II"
    "CSC 549 – Advanced Algorithm Design and Analysis"
    "CSC 550 – Operating Systems"
    "CSC 560 – Database Systems"
    "CSC 566 – Topics in Advanced Data Mining"
    "CSC 569 – Distributed Computing"
    "CSC 570 – Current Topics in Computer Science"
    "CSC 572 – Computer Graphics"
    "CSC 574 – Advanced Compute Shaders in Computer Graphics"
    "CSC 580 – Artificial Intelligence"
    "CSC 581 – Computer Support for Knowledge Management"
    "CSC 582 – Computational Linguistics"
    "CSC 587 – Advanced Deep Learning"
    "CSC 590 – Thesis Seminar"
    "CSC 593 – Cooperative Education Experience"
    "CSC 594 – Cooperative Education Experience"
    "CSC 595 – Cooperative Education Experience"
    "CSC 596 – Research in Computer Science I"
    "CSC 597 – Research in Computer Science II"
    "CSC 599 – Thesis")))

(define cpe-courses
  '("CPE 100 – Computer Engineering Orientation"
    "CPE 133 – Digital Design"
    "CPE 200 – Special Problems for Undergraduates"
    "CPE 225 – Introduction to Computer Organization"
    "CPE 233 – Computer Design and Assembly Language Programming"
    "CPE 290 – Selected Topics"
    "CPE 315 – Computer Architecture"
    "CPE 316 – Microcontrollers and Embedded Applications"
    "CPE 333 – Computer Hardware Architecture and Design"
    "CPE 350 – Capstone I"
    "CPE 400 – Special Problems for Undergraduates"
    "CPE 414 – Robotic Systems Integration"
    "CPE 416 – Autonomous Mobile Robotics"
    "CPE 419 – Applied Parallel Computing"
    "CPE 422 – Network Security"
    "CPE 425 – Wireless Security"
    "CPE 426 – Introduction to Hardware Security"
    "CPE 439 – Introduction to Real-Time Operating Systems"
    "CPE 442 – Real Time Embedded Systems"
    "CPE 446 – Design of Fault-Tolerant Digital Systems"
    "CPE 447 – Stringed Musical Instrument Acoustics, Mechanics, and Transducer Design"
    "CPE 450 – Capstone II"
    "CPE 461 – Senior Project I"
    "CPE 462 – Senior Project II"
    "CPE 464 – Introduction to Computer Networks"
    "CPE 465 – Advanced Computer Networks"
    "CPE 469 – Distributed Systems"
    "CPE 470 – Selected Advanced Topics"
    "CPE 479 – Selected Advanced Laboratory"
    "CPE 493 – Cooperative Education Experience"
    "CPE 494 – Cooperative Education Experience"
    "CPE 495 – Cooperative Education Experience"
    "CPE 515 – Computer Architecture"
    "CPE 521 – Computer Systems"
    "CPE 522 – Advanced Real-Time Operating Systems Design"
    "CPE 523 – Digital Systems Design"
    "CPE 542 – Advanced Real Time Embedded Systems"
    "CPE 564 – Computer Networks: Research Topics"
    "CSC 225 – Introduction to Computer Organization"
    "CSC 422 – Network Security"
    "CSC 425 – Wireless Security"
    "CSC 469 – Distributed Systems"
    "CSC 515 – Computer Architecture"
    "CSC 564 – Computer Networks: Research Topics"))