#lang typed/racket

(require scramble/regexp
         csse-scheduling/canonicalize)

(provide cs-dept-courses
         cpe-dept-courses
         ee-dept-courses
         data-dept-courses)

(define catalog : CatalogCycle "2026-2028")

;; list copy-pasted from the result of running extract-course-list.rkt

(define (parse-clss-course-desc-row [row : String]) : (U False Course-Id)
  (match row
    [(regexp (px ^
                 (report (+ (chars [#\A #\Z])))
                 " "
                 (report (+ (chars [#\0 #\9]
                                   [#\A #\Z])))
                 " – " ;; that's not a regular hyphen...
                 )
             (list _ subject num))
     ;; subject cannot be false, by defn of regexp
     (match (list subject num)
       [(list _ "2IP") #f] ;; EE has "study abroad" courses in their catalog?
       [(list "EE" "4IP") #f]
       [(list "STAT" _) #f] ;; ignore all stats courses
       [other
        (canonicalize catalog (cast subject String) (cast num String))])]
    ))

;; are these two sets non-intersecting?
(: separate? (All (T) ((Listof T) (Listof T) -> Boolean)))
(define (separate? a b)
  (set-empty? (set-intersect a b)))

;; are all of the sets in the list independent?
(define (all-independent? [los : (Listof (Listof String))]) : Boolean
  (cond [(empty? los) #t]
        [else
         (and (andmap (λ ([s : (Listof String)]) (separate? s (first los))) (rest los))
              (all-independent? (rest los)))]))

;; the courses scheduled by the CS department
;; this list captured on 2025-01-29
(define cs-dept-courses
  (filter-map
   parse-clss-course-desc-row
   '("COM 1100 – Introduction to Computers"
     "COM 1107 – Programming in R"
     "COM 1195 – Special Topics"
     "COM 2210 – Engineering Computer Programming"
     "COM 2210L – Oceanography Computer Programming Laboratory"
     "COM 2220L – Programming Applications for Engineering Technology Lab"
     "CSC 2IP – Study Abroad"
     "CSC 4IP – Study Abroad"
     "CSC 5IP – Study Abroad"
     "CSC 1000 – Computing Majors Orientation"
     "CSC 1001 – Fundamentals of Computer Science"
     "CSC 1001L – Fundamentals of Computer Science Laboratory"
     "CSC 1024 – Introduction to Computing"
     "CSC 1031 – Programming for Engineers"
     "CSC 1032 – Programming for Scientists and Engineers"
     "CSC 2001 – Data Structures"
     "CSC 2001L – Data Structures Laboratory"
     "CSC 2050 – System Software Mechanics"
     "CSC 2200 – Special Problems for Undergraduates"
     "CSC 2270 – Special Topics"
     "CSC 2600 – Computing with Data"
     "CSC 3000 – Transfer Student Orientation and Workshop"
     "CSC 3001 – Modern Application Development"
     "CSC 3100 – Software Engineering"
     "CSC 3104 – Software Engineering without Programming"
     "CSC 3111 – Computational Thinking for Educators"
     "CSC 3112 – Software Design and Data Structures for Educators"
     "CSC 3113 – Teaching Computing"
     "CSC 3200 – Practical Computer Security for Everyone"
     "CSC 3201 – Introduction to Computer Security"
     "CSC 3203 – Cryptography Engineering and Applications"
     "CSC 3250 – Introduction to Privacy: Policy and Technology"
     "CSC 3300 – Programming Languages"
     "CSC 3445 – Theory of Computation"
     "CSC 3449 – Algorithms and Complexity"
     "CSC 3660 – Introduction to Databases"
     "CSC 3662 – Introduction to Non-Relational Database Systems"
     "CSC 3665 – Introduction to Database Management Systems"
     "CSC 3710 – Game Design and Development"
     "CSC 3760 – Introduction to Mixed Reality"
     "CSC 3780 – Game Engineering and Critical Analysis"
     "CSC 4036 – Mobile Application Development"
     "CSC 4037 – Web Development"
     "CSC 4091 – Seminars in Computer Science"
     "CSC 4092 – Research Experience in Computer Science"
     "CSC 4093 – Projects in Computer Science"
     "CSC 4100 – Software Evaluation"
     "CSC 4160 – Software Engineering Capstone I"
     "CSC 4161 – Senior Project - Software Engineering Capstone II"
     "CSC 4170 – Special Advanced Topics in Software Engineering"
     "CSC 4184 – User-Centered UI/UX Design"
     "CSC 4186 – Human-Computer Interaction"
     "CSC 4191 – Seminars in Software Engineering"
     "CSC 4192 – Research Experience in Software Engineering"
     "CSC 4193 – Projects in Software Engineering"
     "CSC 4210 – Software Security"
     "CSC 4212 – Malware Design and Analysis"
     "CSC 4214 – Binary Exploitation: Tools and Techniques"
     "CSC 4230 – Web and Cloud Security"
     "CSC 4260 – Interdisciplinary Privacy and Security Capstone I"
     "CSC 4261 – Senior Project - Privacy and Security Capstone II"
     "CSC 4270 – Special Advanced Topics in Computer Security"
     "CSC 4291 – Seminars in Privacy and Security"
     "CSC 4292 – Research Experience in Privacy and Security"
     "CSC 4293 – Projects in Privacy and Security"
     "CSC 4310 – Compiler Construction"
     "CSC 4400 – Special Problems"
     "CSC 4431 – Computing for Interactive Arts Capstone I"
     "CSC 4432 – Computing for Interactive Arts Capstone II"
     "CSC 4448 – Bioinformatics Algorithms"
     "CSC 4460 – Senior Project"
     "CSC 4461 – Senior Project - Research"
     "CSC 4470 – Special Advanced Topics"
     "CSC 4471 – Special Advanced Laboratory"
     "CSC 4472 – Special Advanced Activity"
     "CSC 4495 – Cooperative Education Experience"
     "CSC 4553 – Introduction to Operating Systems"
     "CSC 4554 – Implementation of Operating Systems"
     "CSC 4570 – Special Advanced Topics in Computer Systems"
     "CSC 4610 – Fundamentals of Machine Learning"
     "CSC 4620 – Foundations and Applications of Deep Learning"
     "CSC 4665 – Database Management Systems Organization"
     "CSC 4667 – Deep Learning"
     "CSC 4669 – Distributed Systems"
     "CSC 4691 – Seminars in Data Engineering"
     "CSC 4692 – Research Experience in Data Engineering"
     "CSC 4693 – Projects in Data Engineering"
     "CSC 4710 – Introduction to Computer Graphics"
     "CSC 4730 – Advanced Rendering Techniques"
     "CSC 4740 – Computer Animation"
     "CSC 4760 – Real-Time 3D Computer Graphics Software"
     "CSC 4770 – Special Advanced Topics in Computer Graphics"
     "CSC 4791 – Seminars in Graphics"
     "CSC 4792 – Research Experience in Graphics"
     "CSC 4793 – Projects in Graphics"
     "CSC 4820 – Natural Language Processing"
     "CSC 4880 – Artificial Intelligence"
     "CSC 4881 – Semantic Computing"
     "CSC 4888 – Computer Vision"
     "CSC 4891 – Seminars in Artificial Intelligence and Machine Learning"
     "CSC 4892 – Research Experience in Artificial Intelligence and Machine Learning"
     "CSC 4893 – Projects in Artificial Intelligence and Machine Learning"
     "CSC 4991 – Seminars in Game Development"
     "CSC 4992 – Research Experience in Game Development"
     "CSC 4993 – Projects in Game Development"
     "CSC 5100 – Modern Software Engineering"
     "CSC 5113 – Computing Education Research and Practice"
     "CSC 5170 – Special Advanced Topics in Software Engineering"
     "CSC 5201 – Computer Security and Privacy"
     "CSC 5210 – Software Security"
     "CSC 5220 – Advanced Network Security and Privacy"
     "CSC 5270 – Special Advanced Topics in Computer Security"
     "CSC 5281 – System Security"
     "CSC 5370 – Special Advanced Topics in Programming Languages"
     "CSC 5445 – Advanced Theory of Decidability and Reducibility"
     "CSC 5447 – Advanced Algorithmic Graph Theory"
     "CSC 5449 – Advanced Algorithm Design and Analysis"
     "CSC 5500 – Directed Study"
     "CSC 5550 – Research in Operating Systems"
     "CSC 5570 – Special Advanced Topics"
     "CSC 5571 – Special Advanced Laboratory"
     "CSC 5572 – Special Advanced Activity"
     "CSC 5590 – Thesis Preparation"
     "CSC 5591 – Research in Computer Science"
     "CSC 5595 – Cooperative Education Experience"
     "CSC 5599 – Thesis"
     "CSC 5660 – Advanced Database Management Systems"
     "CSC 5666 – Advanced Machine Learning"
     "CSC 5669 – Distributed Computing"
     "CSC 5670 – Special Advanced Topics in Computer Systems"
     "CSC 5710 – Computer Graphics"
     "CSC 5740 – Advanced Compute Shaders in Computer Graphics"
     "CSC 5770 – Special Advanced Topics in Computer Graphics"
     "CSC 5820 – Computational Linguistics"
     "CSC 5870 – Special Advanced Topics in Artificial Intelligence"
     "CSC 5880 – Artificial Intelligence"
     "CSC 5887 – Advanced Deep Learning"
     "CSC S3100 – Software Engineering")))

;; this list captured on 2026-01-21
(define cpe-dept-courses
  (filter-map
   parse-clss-course-desc-row
   '("CPE 2IP – Study Abroad"
     "CPE 4IP – Study Abroad"
     "CPE 1000 – Computing Majors Orientation"
     "CPE 1024 – Introduction to Computing"
     "CPE 2050 – System Software Mechanics"
     "CPE 2300 – Introduction to Computer Systems"
     "CPE 2301 – Introduction to HDL and Digital Design Laboratory"
     "CPE 3160 – Microcontrollers and Embedded Applications"
     "CPE 3201 – Introduction to Computer Security"
     "CPE 3300 – Computer Architecture"
     "CPE 3345 – Quantum Computing"
     "CPE 4140 – Robotic Systems Integration"
     "CPE 4160 – Autonomous Mobile Robotics"
     "CPE 4180 – Advanced Microcontrollers and Embedded Applications"
     "CPE 4190 – Applied Parallel Computing"
     "CPE 4220 – Network Security"
     "CPE 4250 – Wireless Security"
     "CPE 4260 – Interdisciplinary Privacy and Security Capstone I"
     "CPE 4261 – Senior Project - Privacy and Security Capstone II"
     "CPE 4280 – Introduction to Hardware Security"
     "CPE 4300 – Advanced Computer Architecture"
     "CPE 4310 – Compiler Construction"
     "CPE 4390 – Introduction to Real-Time Operating Systems"
     "CPE 4400 – Special Problems for Undergraduates"
     "CPE 4420 – High-Performance Embedded Systems"
     "CPE 4455 – Design of Fault-Tolerant Systems"
     "CPE 4460 – Capstone Senior Project I"
     "CPE 4461 – Capstone Senior Project II"
     "CPE 4464 – Introduction to Computer Networks"
     "CPE 4465 – Advanced Computer Networks"
     "CPE 4470 – Special Advanced Topics"
     "CPE 4471 – Special Advanced Laboratory"
     "CPE 4472 – Special Advanced Activity"
     "CPE 4491 – Seminar in Computer Engineering"
     "CPE 4492 – Research Experience in Computer Engineering"
     "CPE 4493 – Projects in Computer Engineering"
     "CPE 4495 – Cooperative Education Experience"
     "CPE 4553 – Introduction to Operating Systems"
     "CPE 4570 – Special Advanced Topics in Computer Systems"
     "CPE 4650 – Scalable Server Implementation and Testing"
     "CPE 4669 – Distributed Systems"
     "CPE 5300 – Computer Microarchitecture"
     "CPE 5350 – Digital Systems Design"
     "CPE 5420 – Advanced High-Performance Embedded Systems"
     "CPE 5564 – Research Topics in Computer Networks"
     "CPE 5660 – Computer Systems"
     "CPE 5669 – Distributed Computing")))

(define ee-dept-courses
  (filter-map
   parse-clss-course-desc-row
   '("EE 2IP – Study Abroad"
     "EE 4IP – Study Abroad"
     "EE 1111 – Introduction to Electrical Engineering"
     "EE 1111L – Introduction to Electrical Engineering Laboratory"
     "EE 2115 – Circuits & Electronics for Non-Majors"
     "EE 2115L – Circuits & Electronics Laboratory for Non-Majors"
     "EE 2200 – Special Problems for Undergraduates"
     "EE 2201 – Electric Circuits for Non-Majors"
     "EE 2211 – Electric Circuit Analysis I"
     "EE 2212 – Electric Circuit Analysis II"
     "EE 2241 – Electric Circuit Analysis Laboratory I"
     "EE 2261 – Introduction to C Programming with a Hardware Emphasis"
     "EE 2262 – Object-Oriented Programming with a Hardware Emphasis"
     "EE 2270 – Special Topics"
     "EE 2271 – Special Laboratory"
     "EE 2328 – Signals and Systems"
     "EE 3255 – Electric Machines and Power Systems"
     "EE 3255L – Electric Machines and Power Systems Laboratory"
     "EE 3302 – Classical Control Systems"
     "EE 3302L – Classical Control Systems Laboratory"
     "EE 3306 – Electronics I"
     "EE 3306L – Electronics Laboratory I"
     "EE 3308 – Electronics II"
     "EE 3308L – Electronics Laboratory II"
     "EE 3322 – Microcontrollers for Everyone"
     "EE 3329 – Cyber-Physical Systems"
     "EE 3335 – Electromagnetic Fields and Transmission"
     "EE 3335L – Electromagnetic Fields and Transmission Laboratory"
     "EE 4314 – Communication Systems"
     "EE 4314L – Communication Systems Laboratory"
     "EE 4400 – Special Problems"
     "EE 4406 – Power System Analysis I"
     "EE 4407 – Power System Analysis II"
     "EE 4410 – Fundamentals of Power Electronics"
     "EE 4412 – Advanced Analog and Mixed-Signal Electronics"
     "EE 4416 – Digital Communication Systems"
     "EE 4417 – Electric Machines"
     "EE 4418 – Photonic Component and System Engineering"
     "EE 4418L – Photonic Engineering Laboratory"
     "EE 4419 – Digital Signal Processing"
     "EE 4420 – Sustainable Energy Generation"
     "EE 4422 – Polymer Electronics Laboratory"
     "EE 4425 – Signal Integrity Electronics and Test Automation"
     "EE 4425L – Signal Integrity Electronics and Test Automation Laboratory"
     "EE 4431 – Computer-Aided Design of VLSI Devices"
     "EE 4433 – Magnetic Apparatus Design"
     "EE 4434 – Transportation Electrification and Energy Storage Systems"
     "EE 4435 – Industrial Power Control and Automation"
     "EE 4440 – Wireless Communications"
     "EE 4440L – Wireless Communications Laboratory"
     "EE 4450 – Solar Photovoltaic System Engineering I"
     "EE 4452 – Advanced Analog and Mixed-Signal Electronics Laboratory"
     "EE 4455 – Design of Fault-Tolerant Systems"
     "EE 4456 – Modern Communication Systems Laboratory"
     "EE 4459 – Electrical Engineering Fundamentals of Engineering Exam"
     "EE 4461 – Senior Project I"
     "EE 4462 – Senior Project II"
     "EE 4463 – Senior Project Design Laboratory I"
     "EE 4464 – Senior Project Design Laboratory II"
     "EE 4465 – Senior Design: Individual Project I"
     "EE 4466 – Senior Design: Individual Project II"
     "EE 4470 – Special Advanced Topics"
     "EE 4471 – Special Advanced Laboratory"
     "EE 4485 – Cooperative Education Experience"
     "EE 4495 – Cooperative Education Experience"
     "EE 4528 – Digital Image Processing"
     "EE 5344 – Phased Array Antennas"
     "EE 5424 – Principles of Remote Sensing and Radar"
     "EE 5428 – Computer Vision"
     "EE 5500 – Individual Study"
     "EE 5502 – Microwave and Millimeter Wave Device and System Electronics"
     "EE 5504 – Software Defined Radio"
     "EE 5509 – Computational Intelligence"
     "EE 5510 – Advanced Power Electronics"
     "EE 5511 – Advanced Electric Machines and Design"
     "EE 5512 – Advanced Control Techniques in Modern Power Systems"
     "EE 5513 – Modern Control Systems"
     "EE 5514 – Advanced Modern Control Systems"
     "EE 5515 – Advanced Digital Signal Processing"
     "EE 5517 – Data Analytics for Cyber-Physical Systems"
     "EE 5518 – Power System Protection"
     "EE 5519 – Electric Power Distribution and Microgrids"
     "EE 5520 – Advanced Solar-Photovoltaic Systems Design"
     "EE 5524 – Solid State Electronics"
     "EE 5525 – Stochastic Processes"
     "EE 5526 – Advanced Digital Communications"
     "EE 5530 – Advanced Photonic Systems"
     "EE 5531 – Advanced VLSI Design and Validation"
     "EE 5532 – VLSI Test Laboratory"
     "EE 5533 – Antennas"
     "EE 5535 – Utility Applications of Power Electronics and Power Quality"
     "EE 5541 – Advanced Microwave and Millimeter-Wave Laboratory"
     "EE 5544 – Solid-state Electronics Laboratory"
     "EE 5563 – Graduate Seminar"
     "EE 5570 – Special Advanced Topics"
     "EE 5571 – Special Advanced Laboratory"
     "EE 5594 – Professional Engineer Examination"
     "EE 5595 – Cooperative Education Experience"
     "EE 5597 – Comprehensive Examination"
     "EE 5599 – Thesis")))

;; captured on 2026-01-21
;; NB IGNORES ALL STAT COURSES
(define data-dept-courses
  (filter-map
   parse-clss-course-desc-row
   '("DAT 1108 – Foundations of Data Science"
     "DAT 1108L – Foundations of Data Science Laboratory"
     "DAT 3308 – Principles and Techniques of Data Science"
     "DATA 2IP – Study Abroad"
     "DATA 1000 – Statistical and Data Literacy"
     "DATA 1264 – Calculus for Data Science I"
     "DATA 1264 – Calculus for Data Science I"
     "DATA 1265 – Calculus for Data Science II"
     "DATA 1810 – Introduction to Statistical Computing with R"
     "DATA 2621 – Introduction to Mathematical Optimization"
     "DATA 3301 – Introduction to Data Science"
     "DATA 3302 – Data Visualization"
     "DATA 3622 – Mathematics of Data Science"
     "DATA 3800 – Introduction to Statistical Computing with SAS and SQL"
     "DATA 3820 – Intermediate Statistical Computing with R"
     "DATA 4011 – Optimization in Julia for Economics and Data Science"
     "DATA 4011A – Julia for Data Analysis Project"
     "DATA 4401 – Data Science Process and Ethics"
     "DATA 4460 – Senior Project - Data Science Capstone"
     "DATA 4461 – Senior Project - Bioinformatics Capstone"
     "DATA 4610 – Fundamentals of Machine Learning"
     "DATA 4620 – Foundations and Applications of Deep Learning"
     "DATA 4632 – Graph Mining"
     "DATA 4720 – Data Science Seminar"
     "DATA 4810 – SAS Certification Preparation: Base Programming"
     "DATA 4820 – SAS Certification Preparation: Advanced Programming"
     "DATA 5550 – Statistical Learning with R"
     "DATA 5800 – Introduction to SAS and SQL for Graduate Students"
     "DATA 5820 – Intermediate Statistical Computing with R for Graduate Students"
     "MTH 1107 – Elementary Statistics"
     "STAT 2IP – Study Abroad"
     "STAT 1000 – Statistical and Data Literacy"
     "STAT 1110 – Applied Statistical Concepts and Methods"
     "STAT 1210 – Business Statistics I"
     "STAT 1210 – Business Statistics I"
     "STAT 1220 – Business Statistics II"
     "STAT 1220 – Business Statistics II"
     "STAT 1510 – Statistics I"
     "STAT 1810 – Introduction to Statistical Computing with R"
     "STAT 2200 – Special Problems for Undergraduates"
     "STAT 2270 – Special Topics"
     "STAT 2610 – Introduction to Probability and Simulation"
     "STAT 3210 – Engineering Statistics"
     "STAT 3310 – Probability and Random Processes for Engineers"
     "STAT 3320 – Statistical Methods for Food Science"
     "STAT 3430 – Applied Regression Analysis"
     "STAT 3520 – Statistics II"
     "STAT 3530 – Applied Linear Models"
     "STAT 3540 – Statistical Methods for Study Design and Analysis"
     "STAT 3710 – Teaching Statistics: Pedagogy, Content, Technology, and Assessment"
     "STAT 3800 – Introduction to Statistical Computing with SAS and SQL"
     "STAT 3820 – Intermediate Statistical Computing with R"
     "STAT 4366 – Statistical Communication, Collaboration, and Consulting"
     "STAT 4400 – Special Problems for Advanced Undergraduates"
     "STAT 4460 – Senior Project: Statistics Capstone"
     "STAT 4470 – Special Advanced Topics"
     "STAT 4610 – Probability Theory"
     "STAT 4620 – Statistical Theory"
     "STAT 4740 – Multilevel and Mixed Modeling"
     "STAT 4750 – Bayesian Reasoning and Methods"
     "STAT 4760 – Statistical Analysis of Time Series"
     "STAT 4770 – Survival Analysis Methods"
     "STAT 4780 – Categorical Data Analysis"
     "STAT 4790 – Applied Multivariate Statistics"
     "STAT 4810 – SAS Certification Preparation: Base Programming"
     "STAT 4820 – SAS Certification Preparation: Advanced Programming"
     "STAT 5110 – Introductory Statistics for Graduate Students"
     "STAT 5120 – Intermediate Statistics for Graduate Students"
     "STAT 5210 – Introduction to Engineering Statistics for Graduate Students"
     "STAT 5430 – Applied Regression Analysis for Graduate Students"
     "STAT 5440 – Statistical Methods for Study Design and Analysis"
     "STAT 5500 – Independent Study"
     "STAT 5530 – Generalized Linear Models"
     "STAT 5550 – Statistical Learning with R"
     "STAT 5566 – Graduate Consulting Practicum"
     "STAT 5570 – Special Advanced Topics"
     "STAT 5590 – Graduate Seminar in Statistics"
     "STAT 5599 – Thesis"
     "STAT 5710 – Applied Stochastic Processes"
     "STAT 5740 – Advanced Design and Analysis of Experiments"
     "STAT 5800 – Introduction to SAS and SQL for Graduate Students"
     "STAT 5820 – Intermediate Statistical Computing with R for Graduate Students")))

;; ouch, not empty:
#;(set-intersect cpe-dept-courses
               ee-dept-courses)

(unless (all-independent?
         (list cs-dept-courses
               cpe-dept-courses
               #;ee-dept-courses
               data-dept-courses))
  (error 'overlap "some departments' CLSS schedulable lists overlap"))

