#lang racket

(require scramble/regexp
         csse-scheduling/canonicalize)

(provide cs-dept-courses
         cpe-dept-courses
         ee-dept-courses
         data-dept-courses)

(define catalog "2022-2026")

;; list copy-pasted from the result of running extract-course-list.rkt

(define (parse-clss-course-desc-row row)
  (match row
    [(regexp (px ^
                 (report (+ (chars [#\A #\Z])))
                 " "
                 (report (+ (chars [#\0 #\9]
                                   [#\A #\Z])))
                 " – " ;; that's not a regular hyphen...
                 )
             (list _ subject num))
     (match (list subject num)
       [(list _ "2IP") #f] ;; EE has "study abroad" courses in their catalog?
       [(list "EE" "4IP") #f]
       [(list "STAT" _) #f] ;; ignore all stats courses
       [other
        (canonicalize catalog subject num)])]
    ))

;; are these two sets non-intersecting?
(define (separate? a b)
  (set-empty? (set-intersect a b)))

;; are all of the sets in the list independent?
(define (all-independent? los)
  (cond [(empty? los) #t]
        [else
         (and (andmap (λ (s) (separate? s (first los))) (rest los))
              (all-independent? (rest los)))]))

;; the courses scheduled by the CS department
;; this list captured on 2025-01-29
(define cs-dept-courses
  (map
   parse-clss-course-desc-row
   '("CPE 101 – Fundamentals of Computer Science"
     "CPE 123 – Introduction to Computing"
     "CPE 202 – Data Structures"
     "CPE 203 – Project-Based Object-Oriented Programming and Design"
     "CPE 321 – Introduction to Computer Security"
     "CPE 357 – Systems Programming"
     "CPE 431 – Compiler Construction"
     "CPE 453 – Introduction to Operating Systems"
     "CPE 454 – Implementation of Operating Systems"
     "CPE 458 – Current Topics in Computer Systems"
     "CPE 471 – Introduction to Computer Graphics"
     "CPE 476 – Real-Time 3D Computer Graphics Software"
     "CPE 569 – Distributed Computing"
     "CSC 101 – Fundamentals of Computer Science"
     "CSC 121 – Computing for All I"
     "CSC 122 – Computing for All II"
     "CSC 123 – Introduction to Computing"
     "CSC 200 – Special Problems for Undergraduates"
     "CSC 202 – Data Structures"
     "CSC 203 – Project-Based Object-Oriented Programming and Design"
     "CSC 231 – Programming for Engineering Students"
     "CSC 232 – Computer Programming for Scientists and Engineers"
     "CSC 234 – C and Unix"
     "CSC 248 – Discrete Structures"
     "CSC 290 – Selected Topics"
     "CSC 300 – Professional Responsibilities"
     "CSC 304 – Software Engineering without Programming"
     "CSC 305 – Individual Software Design and Development"
     "CSC 307 – Introduction to Software Engineering"
     "CSC 308 – Software Engineering I"
     "CSC 309 – Software Engineering II"
     "CSC 312 – Computational Thinking for Educators"
     "CSC 313 – Teaching Computing"
     "CSC 314 – Software Design and Data Structures for Educators"
     "CSC 320 – Practical Computer Security for Everyone"
     "CSC 321 – Introduction to Computer Security"
     "CSC 323 – Cryptography Engineering"
     "CSC 325 – Introduction to Privacy: Policy and Technology"
     "CSC 344 – Music Programming"
     "CSC 349 – Design and  Analysis of Algorithms"
     "CSC 350 – Computing for Interactive Arts Capstone I"
     "CSC 357 – Systems Programming"
     "CSC 364 – Introduction to Networked, Distributed, and Parallel Computing"
     "CSC 365 – Introduction to Database Systems"
     "CSC 366 – Database Modeling, Design and Implementation"
     "CSC 369 – Introduction to Distributed Computing"
     "CSC 371 – Game Design"
     "CSC 377 – Introduction to Mixed Reality"
     "CSC 378 – Interactive Entertainment Engineering"
     "CSC 400 – Special Problems"
     "CSC 402 – Software Requirements Engineering"
     "CSC 405 – Software Construction"
     "CSC 406 – Senior Project - Software Deployment"
     "CSC 409 – Current Topics in Software Engineering"
     "CSC 410 – Software Evaluation"
     "CSC 421 – Binary Exploitation: Tools and Techniques"
     "CSC 424 – Software Security"
     "CSC 429 – Current Topics in Computer Security"
     "CSC 430 – Programming Languages"
     "CSC 431 – Compiler Construction"
     "CSC 436 – Mobile Application Development"
     "CSC 437 – Dynamic Web Development"
     "CSC 445 – Theory of Computation I"
     "CSC 448 – Bioinformatics Algorithms"
     "CSC 450 – Computing for Interactive Arts Capstone II"
     "CSC 453 – Introduction to Operating Systems"
     "CSC 454 – Implementation of Operating Systems"
     "CSC 458 – Current Topics in Computer Systems"
     "CSC 466 – Knowledge Discovery from Data"
     "CSC 468 – Database Management Systems Implementation"
     "CSC 471 – Introduction to Computer Graphics"
     "CSC 473 – Advanced Rendering Techniques"
     "CSC 474 – Computer Animation"
     "CSC 476 – Real-Time 3D Computer Graphics Software"
     "CSC 477 – Scientific and Information Visualization"
     "CSC 478 – Current Topics in Computer Graphics"
     "CSC 480 – Artificial Intelligence"
     "CSC 481 – Knowledge Based Systems"
     "CSC 482 – Speech and Language Processing"
     "CSC 484 – User-Centered Interface Design and Development"
     "CSC 486 – Human-Computer Interaction Theory and Design"
     "CSC 487 – Deep Learning"
     "CSC 490 – Selected Advanced Topics"
     "CSC 491 – Senior Project I"
     "CSC 492 – Senior Project II"
     "CSC 493 – Cooperative Education Experience"
     "CSC 496 – Selected Advanced Laboratory"
     "CSC 497 – Research Senior Project I"
     "CSC 498 – Research Senior Project II"
     "CSC 500 – Directed Study"
     "CSC 508 – Software Engineering I"
     "CSC 509 – Software Engineering II"
     "CSC 513 – Computing Education Research and Practice"
     "CSC 521 – Computer Security"
     "CSC 522 – Advanced Network Security"
     "CSC 524 – System Security"
     "CSC 530 – Languages and Translators"
     "CSC 540 – Theory of Computation II"
     "CSC 549 – Advanced Algorithm Design and Analysis"
     "CSC 550 – Operating Systems"
     "CSC 560 – Database Systems"
     "CSC 566 – Topics in Advanced Data Mining"
     "CSC 569 – Distributed Computing"
     "CSC 570 – Current Topics in Computer Science"
     "CSC 572 – Computer Graphics"
     "CSC 574 – Advanced Compute Shaders in Computer Graphics"
     "CSC 580 – Artificial Intelligence"
     "CSC 581 – Computer Support for Knowledge Management"
     "CSC 582 – Computational Linguistics"
     "CSC 587 – Advanced Deep Learning"
     "CSC 590 – Thesis Seminar"
     "CSC 593 – Cooperative Education Experience"
     "CSC 594 – Cooperative Education Experience"
     "CSC 595 – Cooperative Education Experience"
     "CSC 596 – Research in Computer Science I"
     "CSC 597 – Research in Computer Science II"
     "CSC 599 – Thesis")))

;; this list captured on 2025-01-29
(define cpe-dept-courses
  (map
   parse-clss-course-desc-row
   '("CPE 100 – Computer Engineering Orientation"
     "CPE 133 – Digital Design"
     "CPE 200 – Special Problems for Undergraduates"
     "CPE 225 – Introduction to Computer Organization"
     "CPE 233 – Computer Design and Assembly Language Programming"
     "CPE 290 – Selected Topics"
     "CPE 315 – Computer Architecture"
     "CPE 316 – Microcontrollers and Embedded Applications"
     "CPE 333 – Computer Hardware Architecture and Design"
     "CPE 350 – Capstone I"
     "CPE 400 – Special Problems for Undergraduates"
     "CPE 414 – Robotic Systems Integration"
     "CPE 416 – Autonomous Mobile Robotics"
     "CPE 419 – Applied Parallel Computing"
     "CPE 422 – Network Security"
     "CPE 425 – Wireless Security"
     "CPE 426 – Introduction to Hardware Security"
     "CPE 439 – Introduction to Real-Time Operating Systems"
     "CPE 442 – Real Time Embedded Systems"
     "CPE 446 – Design of Fault-Tolerant Digital Systems"
     "CPE 447 – Stringed Musical Instrument Acoustics, Mechanics, and Transducer Design"
     "CPE 450 – Capstone II"
     "CPE 461 – Senior Project I"
     "CPE 462 – Senior Project II"
     "CPE 464 – Introduction to Computer Networks"
     "CPE 465 – Advanced Computer Networks"
     "CPE 469 – Distributed Systems"
     "CPE 470 – Selected Advanced Topics"
     "CPE 479 – Selected Advanced Laboratory"
     "CPE 493 – Cooperative Education Experience"
     "CPE 494 – Cooperative Education Experience"
     "CPE 495 – Cooperative Education Experience"
     "CPE 515 – Computer Architecture"
     "CPE 521 – Computer Systems"
     "CPE 522 – Advanced Real-Time Operating Systems Design"
     "CPE 523 – Digital Systems Design"
     "CPE 542 – Advanced Real Time Embedded Systems"
     "CPE 564 – Computer Networks: Research Topics"
     "CSC 225 – Introduction to Computer Organization"
     "CSC 422 – Network Security"
     "CSC 425 – Wireless Security"
     "CSC 469 – Distributed Systems"
     "CSC 515 – Computer Architecture"
     "CSC 564 – Computer Networks: Research Topics")))

(define ee-dept-courses
  (filter-map
   parse-clss-course-desc-row
   '("CPE 327 – Digital Signals and Systems"
     "CPE 328 – Discrete Time Signals and Systems"
     "CPE 329 – Microcontroller-Based Systems Design"
     "CPE 336 – Microprocessor System Design"
     "CPE 367 – Digital Signals and Systems Laboratory"
     "CPE 368 – Signals and Systems Laboratory"
     "CPE 428 – Computer Vision"
     "CPE 432 – Digital Control Systems"
     "CPE 441 – Computer-Aided Design of VLSI Devices"
     "CPE 472 – Digital Control Systems Laboratory"
     "CPE 532 – VLSI Circuit Testing"
     "CPE 541 – Advanced VLSI Design"
     "EE 2IP – Study Abroad"
     "EE 4IP – Study Abroad"
     "EE 111 – Introduction to Electrical Engineering"
     "EE 112 – Electric Circuit Analysis I"
     "EE 113 – Electric Circuit Analysis I"
     "EE 115 – Electrical and Electronic Circuits I"
     "EE 133 – Digital Design"
     "EE 143 – Electronics Manufacturing and Circuit Analysis Laboratory"
     "EE 145 – Electrical and Electronic Circuits I Laboratory"
     "EE 151 – Introduction to Electrical Engineering Laboratory"
     "EE 200 – Special Problems"
     "EE 201 – Electric Circuit Theory"
     "EE 211 – Electric Circuit Analysis II"
     "EE 212 – Electric Circuit Analysis III"
     "EE 215 – Electrical and Electronic Circuits II"
     "EE 228 – Continuous-Time Signals and Systems"
     "EE 233 – Computer Design and Assembly Language Programming"
     "EE 241 – Electric Circuit Analysis Laboratory II"
     "EE 242 – Electric Circuit Analysis Laboratory III"
     "EE 245 – Electrical and Electronic Circuits II Laboratory"
     "EE 251 – Electric Circuits Laboratory"
     "EE 255 – Energy Conversion Electromagnetics"
     "EE 261 – Intro C Programming with a Hardware Emphasis"
     "EE 262 – Intro C++ Programming with a Hardware Emphasis"
     "EE 270 – Selected Topics"
     "EE 271 – Selected Laboratory"
     "EE 295 – Energy Conversion Electromagnetics Laboratory"
     "EE 302 – Classical Control Systems"
     "EE 306 – Semiconductor Device Electronics"
     "EE 307 – Digital Electronics and Integrated Circuits"
     "EE 308 – Analog Electronics and Integrated Circuits"
     "EE 314 – Introduction to Communication Systems"
     "EE 315 – Electrical and Electronic Circuits III"
     "EE 321 – Electronics"
     "EE 322 – Microcontrollers for Everyone"
     "EE 327 – Digital Signals and Systems"
     "EE 328 – Discrete Time Signals and Systems"
     "EE 329 – Microcontroller-Based Systems Design"
     "EE 335 – Electromagnetic Fields and Transmission"
     "EE 336 – Microprocessor System Design"
     "EE 342 – Classical Control Systems Laboratory"
     "EE 346 – Semiconductor Device Electronics Laboratory"
     "EE 347 – Digital Electronics and Integrated Circuits Laboratory"
     "EE 348 – Analog Electronics and Integrated Circuits Laboratory"
     "EE 361 – Electronics Laboratory"
     "EE 367 – Digital Signals and Systems Laboratory"
     "EE 368 – Signals and Systems Laboratory"
     "EE 375 – Electromagnetic Fields and Transmission Laboratory"
     "EE 400 – Special Problems"
     "EE 402 – Electromagnetic Waves"
     "EE 403 – Introduction to Photonics and Fiber Optics"
     "EE 405 – High Frequency Amplifier Design"
     "EE 406 – Power Systems Analysis I"
     "EE 407 – Power Systems Analysis II"
     "EE 409 – Electronic Design"
     "EE 410 – Power Electronics I"
     "EE 411 – Power Electronics II"
     "EE 412 – Advanced Analog Circuits"
     "EE 413 – Advanced Electronic Design"
     "EE 414 – Robotic Systems Integration"
     "EE 415 – Communication Systems Design"
     "EE 416 – Digital Communication Systems"
     "EE 417 – Alternating Current Machines"
     "EE 418 – Photonic Engineering"
     "EE 419 – Digital Signal Processing"
     "EE 420 – Sustainable Electric Energy Conversion"
     "EE 422 – Polymer Electronics Laboratory"
     "EE 423 – Micro/Nano Fabrication"
     "EE 424 – Introduction to Remote Sensing"
     "EE 425 – Analog Filter Design"
     "EE 428 – Computer Vision"
     "EE 431 – Computer-Aided Design of VLSI Devices"
     "EE 432 – Digital Control Systems"
     "EE 433 – Introduction to Magnetic Design"
     "EE 434 – Automotive Engineering for a Sustainable Future"
     "EE 435 – Industrial Power Control and Automation"
     "EE 439 – Introduction to Real-Time Operating Systems"
     "EE 440 – Wireless Communications"
     "EE 442 – Real Time Embedded Systems"
     "EE 443 – Introduction to Photonics and Fiber Optics Laboratory"
     "EE 444 – Power Systems Laboratory"
     "EE 445 – High Frequency Amplifier Design Laboratory"
     "EE 446 – Design of Fault-Tolerant Digital Systems"
     "EE 447 – Stringed Musical Instrument Acoustics, Mechanics, and Transducer Design"
     "EE 449 – Electronic Design Laboratory"
     "EE 450 – Solar Photovoltaic System Engineering"
     "EE 452 – Advanced Analog Circuits Laboratory"
     "EE 455 – Analog Filter Design Laboratory"
     "EE 456 – Digital Communication Systems Laboratory"
     "EE 458 – Photonic Engineering Laboratory"
     "EE 459 – Digital Signal Processing Laboratory"
     "EE 460 – Senior Project Preparation"
     "EE 461 – Senior Project I"
     "EE 462 – Senior Project II"
     "EE 463 – Senior Project Design Laboratory I"
     "EE 464 – Senior Project Design Laboratory II"
     "EE 470 – Selected Advanced Topics"
     "EE 471 – Selected Advanced Laboratory"
     "EE 472 – Digital Control Systems Laboratory"
     "EE 473 – Microfabrication Laboratory"
     "EE 475 – Communication Networks and Systems Laboratory"
     "EE 480 – Wireless Communications Laboratory"
     "EE 493 – Cooperative Education Experience"
     "EE 494 – Cooperative Education Experience"
     "EE 495 – Cooperative Education Experience"
     "EE 500 – Individual Study"
     "EE 502 – Microwave Component and System Engineering"
     "EE 504 – Software Defined Radio"
     "EE 509 – Computational Intelligence"
     "EE 511 – Electric Machines Theory"
     "EE 513 – Control Systems Theory"
     "EE 514 – Advanced Topics in Automatic Control"
     "EE 515 – Discrete Time Filters"
     "EE 516 – Pattern Recognition"
     "EE 518 – Power System Protection"
     "EE 519 – Advanced Analysis of Power Systems"
     "EE 520 – Advanced Solar-Photovoltaic Systems Design"
     "EE 521 – Computer Systems"
     "EE 522 – Advanced Real-Time Operating Systems Design"
     "EE 523 – Digital Systems Design"
     "EE 524 – Solid State Electronics"
     "EE 525 – Stochastic Processes"
     "EE 526 – Advanced Digital Communications"
     "EE 527 – Advanced Topics in Power Electronics"
     "EE 528 – Digital Image Processing"
     "EE 529 – Microwave Device Electronics"
     "EE 530 – Fourier Optics"
     "EE 531 – Advanced VLSI Design"
     "EE 532 – VLSI Circuit Testing"
     "EE 533 – Antennas"
     "EE 534 – Advanced Photonic Systems"
     "EE 541 – Advanced Microwave Laboratory"
     "EE 542 – Advanced Real Time Embedded Systems"
     "EE 544 – Solid-state Electronics and VLSI Laboratory"
     "EE 563 – Graduate Seminar"
     "EE 570 – Selected Advanced Topics"
     "EE 571 – Selected Advanced Laboratory"
     "EE 594 – Cooperative Education Experience"
     "EE 595 – Cooperative Education Experience"
     "EE 599 – Design Project (Thesis)")))

;; captured on 2025-01-03
;; NB IGNORES ALL STAT COURSES
(define data-dept-courses
  (filter-map
   parse-clss-course-desc-row
   '("DATA 2IP – Study Abroad"
     "DATA 100 – Data Science for All I"
     "DATA 301 – Introduction to Data Science"
     "DATA 401 – Data Science Process and Ethics"
     "DATA 402 – Mathematical Foundations of Data Science"
     "DATA 403 – Data Science Projects Laboratory"
     "DATA 441 – Bioinformatics Capstone I"
     "DATA 442 – Bioinformatics Capstone II"
     "DATA 451 – Data Science Capstone I"
     "DATA 452 – Data Science Capstone II"
     "DATA 472 – Data Science Seminar"
     "STAT 2IP – Study Abroad"
     "STAT 130 – Introduction to Statistical Reasoning"
     "STAT 150 – Introduction to the Discipline of Statistics"
     "STAT 200 – Special Problems for Undergraduates"
     "STAT 217 – Introduction to Statistical Concepts and Methods"
     "STAT 218 – Applied Statistics for the Life Sciences"
     "STAT 251 – Statistical Inference for Management I"
     "STAT 252 – Statistical Inference for Management II"
     "STAT 270 – Selected Topics"
     "STAT 301 – Statistics I"
     "STAT 302 – Statistics II"
     "STAT 305 – Introduction to Probability and Simulation"
     "STAT 312 – Statistical Methods for Engineers"
     "STAT 313 – Applied Experimental Design and Regression Models"
     "STAT 314 – Statistical Methods for Food Science"
     "STAT 321 – Probability and Statistics for Engineers and Scientists"
     "STAT 323 – Design and Analysis of Experiments I"
     "STAT 324 – Applied Regression Analysis"
     "STAT 330 – Statistical Computing with SAS"
     "STAT 331 – Statistical Computing with R"
     "STAT 334 – Applied Linear Models"
     "STAT 350 – Probability and Random Processes for Engineers"
     "STAT 365 – Statistical Communication"
     "STAT 400 – Special Problems for Advanced Undergraduates"
     "STAT 405 – Applied Probability Models"
     "STAT 410 – Statistics Education: Pedagogy, Content, Technology, and Assessment"
     "STAT 414 – Multilevel and Mixed Modeling"
     "STAT 415 – Bayesian Reasoning and Methods"
     "STAT 416 – Statistical Analysis of Time Series"
     "STAT 417 – Survival Analysis Methods"
     "STAT 418 – Categorical Data Analysis"
     "STAT 419 – Applied Multivariate Statistics"
     "STAT 421 – Survey Sampling and Methodology"
     "STAT 423 – Design and Analysis of Experiments II"
     "STAT 425 – Probability Theory"
     "STAT 426 – Estimation and Sampling Theory"
     "STAT 427 – Mathematical Statistics"
     "STAT 431 – Advanced Statistical Computing with R"
     "STAT 434 – Statistical Learning: Methods and Applications"
     "STAT 440 – SAS Certification Preparation"
     "STAT 441 – SAS Advanced Certification Preparation"
     "STAT 461 – Senior Project I"
     "STAT 462 – Senior Project II"
     "STAT 465 – Statistical Consulting"
     "STAT 466 – Senior Project - Statistical Consulting"
     "STAT 470 – Selected Advanced Topics"
     "STAT 485 – Cooperative Education Experience"
     "STAT 495 – Cooperative Education Experience"
     "STAT 500 – Independent Study"
     "STAT 511 – Statistical Methods"
     "STAT 513 – Applied Experimental Design and Regression Models"
     "STAT 523 – Design and Analysis of Experiments I"
     "STAT 524 – Applied Regression Analysis"
     "STAT 530 – Statistical Computing with SAS"
     "STAT 531 – Statistical Computing with R"
     "STAT 541 – Advanced Statistical Computing with R"
     "STAT 542 – Statistical Methods for Engineers"
     "STAT 543 – Advanced Design and Analysis of Experiments"
     "STAT 545 – Applied Stochastic Processes"
     "STAT 550 – Generalized Linear Models"
     "STAT 551 – Statistical Learning with R"
     "STAT 566 – Graduate Consulting Practicum"
     "STAT 570 – Selected Advanced Topics"
     "STAT 590 – Graduate Seminar in Statistics"
     "STAT 599 – Thesis")))

;; ouch, not empty:
(set-intersect cpe-dept-courses
               ee-dept-courses)

(unless (all-independent?
         (list cs-dept-courses
               cpe-dept-courses
               #;ee-dept-courses
               data-dept-courses))
  (error 'overlap "some departments' CLSS schedulable lists overlap"))

